"""Configuration management for deployments."""

import json
import os
import re
from dataclasses import dataclass, field
from pathlib import Path
from typing import Optional, List, Dict, Any


@dataclass
class DeploymentConfig:
    """Configuration for a deployment."""

    # Provider selection
    provider: str = "hetzner"  # hetzner, aws, or digitalocean

    # Required (common)
    project_name: str = ""
    git_user_name: str = ""
    git_user_email: str = ""

    # SSH
    ssh_public_key_path: str = ""  # Empty = generate new

    # Hetzner Cloud
    hetzner_token: str = ""
    hetzner_server_type: str = "cx32"
    hetzner_location: str = "fsn1"
    hetzner_image: str = "ubuntu-24.04"

    # AWS
    aws_access_key: str = ""
    aws_secret_key: str = ""
    aws_instance_type: str = "t3.medium"
    aws_region: str = "us-east-1"

    # DigitalOcean
    digitalocean_token: str = ""
    digitalocean_size: str = "s-2vcpu-4gb"
    digitalocean_region: str = "nyc1"

    # Gas Town
    gastown_repo: str = "https://github.com/steveyegge/gastown.git"
    gastown_branch: str = "main"

    # Claude
    anthropic_api_key: str = ""

    # Firewall
    enable_firewall: bool = True
    firewall_allowed_ips: List[str] = field(default_factory=list)

    # Services
    enable_systemd_services: bool = False


def get_root_dir() -> Path:
    """Get the root directory of roughneck."""
    # Assumes this file is in lib/
    return Path(__file__).parent.parent


def get_deployments_dir() -> Path:
    """Get the deployments directory."""
    return get_root_dir() / "deployments"


def get_deployment_dir(name: str) -> Path:
    """Get directory for a specific deployment."""
    return get_deployments_dir() / name


def list_deployments() -> List[str]:
    """List all deployment names."""
    deployments_dir = get_deployments_dir()
    if not deployments_dir.exists():
        return []

    deployments = []
    for item in deployments_dir.iterdir():
        if item.is_dir() and (item / "terraform.tfvars").exists():
            deployments.append(item.name)
    return sorted(deployments)


def deployment_exists(name: str) -> bool:
    """Check if a deployment exists."""
    return (get_deployment_dir(name) / "terraform.tfvars").exists()


def has_state_file(name: str) -> bool:
    """Check if a deployment has terraform state."""
    return (get_deployment_dir(name) / "terraform.tfstate").exists()


def get_tfvars_path(name: str) -> str:
    """Get the path to a deployment's tfvars file."""
    return str(get_deployment_dir(name) / "terraform.tfvars")


def get_deployment_state(name: str) -> Optional[Dict[str, Any]]:
    """Get terraform state for a deployment, if it exists."""
    state_file = get_deployment_dir(name) / "terraform.tfstate"
    if not state_file.exists():
        return None
    try:
        with open(state_file) as f:
            return json.load(f)
    except (json.JSONDecodeError, OSError):
        return None


def get_deployment_ip(name: str) -> Optional[str]:
    """Get the IP address for a deployment."""
    state = get_deployment_state(name)
    if not state:
        return None
    try:
        return state["outputs"]["server_ip"]["value"]
    except (KeyError, TypeError):
        return None


def get_deployment_provider(name: str) -> Optional[str]:
    """Get the provider for a deployment."""
    config = read_tfvars(name)
    if config:
        return config.provider
    return None


def get_private_key_path(name: str) -> Optional[str]:
    """Get the private key path for a deployment."""
    # Check for generated key
    generated = get_deployment_dir(name) / "generated_key"
    if generated.exists():
        return str(generated)

    # Check tfvars for custom key
    config = read_tfvars(name)
    if config and config.ssh_public_key_path:
        # Convert .pub path to private key path
        return config.ssh_public_key_path.replace(".pub", "")

    return None


def write_tfvars(name: str, config: DeploymentConfig) -> None:
    """Write terraform.tfvars for a deployment."""
    deploy_dir = get_deployment_dir(name)
    deploy_dir.mkdir(parents=True, exist_ok=True)

    # Format allowed IPs as HCL list
    allowed_ips_hcl = "[" + ", ".join(f'"{ip}"' for ip in config.firewall_allowed_ips) + "]"

    lines = [
        "# Generated by roughneck",
        "",
        "# Provider",
        f'provider_name = "{config.provider}"',
        "",
    ]

    # Provider-specific config
    if config.provider == "hetzner":
        lines.extend([
            "# Hetzner Cloud",
            f'hetzner_token       = "{config.hetzner_token}"',
            f'hetzner_server_type = "{config.hetzner_server_type}"',
            f'hetzner_location    = "{config.hetzner_location}"',
            f'hetzner_image       = "{config.hetzner_image}"',
        ])
    elif config.provider == "aws":
        lines.extend([
            "# AWS",
            f'aws_access_key    = "{config.aws_access_key}"',
            f'aws_secret_key    = "{config.aws_secret_key}"',
            f'aws_instance_type = "{config.aws_instance_type}"',
            f'aws_region        = "{config.aws_region}"',
        ])
    elif config.provider == "digitalocean":
        lines.extend([
            "# DigitalOcean",
            f'digitalocean_token  = "{config.digitalocean_token}"',
            f'digitalocean_size   = "{config.digitalocean_size}"',
            f'digitalocean_region = "{config.digitalocean_region}"',
        ])

    lines.extend([
        "",
        "# Common",
        f'project_name   = "{config.project_name}"',
        f'git_user_name  = "{config.git_user_name}"',
        f'git_user_email = "{config.git_user_email}"',
        "",
        "# SSH",
        f'ssh_public_key_path = "{config.ssh_public_key_path}"',
        "",
        "# Firewall",
        f"enable_firewall      = {str(config.enable_firewall).lower()}",
        f"firewall_allowed_ips = {allowed_ips_hcl}",
        "",
        "# Gas Town",
        f'gastown_repo   = "{config.gastown_repo}"',
        f'gastown_branch = "{config.gastown_branch}"',
        "",
        "# Claude",
        f'anthropic_api_key = "{config.anthropic_api_key}"',
        "",
        "# Services",
        f"enable_systemd_services = {str(config.enable_systemd_services).lower()}",
    ])

    tfvars_path = deploy_dir / "terraform.tfvars"
    with open(tfvars_path, "w") as f:
        f.write("\n".join(lines) + "\n")


def read_tfvars(name: str) -> Optional[DeploymentConfig]:
    """Read terraform.tfvars for a deployment."""
    tfvars_path = get_deployment_dir(name) / "terraform.tfvars"
    if not tfvars_path.exists():
        return None

    config = DeploymentConfig()
    try:
        with open(tfvars_path) as f:
            content = f.read()

        # Parse HCL-style tfvars (simple key = "value" format)
        for line in content.split("\n"):
            line = line.strip()
            if not line or line.startswith("#"):
                continue

            match = re.match(r'(\w+)\s*=\s*"([^"]*)"', line)
            if match:
                key, value = match.groups()
                # Map provider_name to provider
                if key == "provider_name":
                    config.provider = value
                elif hasattr(config, key):
                    setattr(config, key, value)
                continue

            # Handle boolean values
            match = re.match(r"(\w+)\s*=\s*(true|false)", line)
            if match:
                key, value = match.groups()
                if hasattr(config, key):
                    setattr(config, key, value == "true")
                continue

            # Handle list values like ["a", "b"]
            match = re.match(r'(\w+)\s*=\s*\[(.*)\]', line)
            if match:
                key, value = match.groups()
                if hasattr(config, key):
                    # Parse list items
                    items = re.findall(r'"([^"]*)"', value)
                    setattr(config, key, items)

        return config
    except OSError:
        return None


def delete_deployment(name: str) -> None:
    """Delete a deployment directory."""
    import shutil

    deploy_dir = get_deployment_dir(name)
    if deploy_dir.exists():
        shutil.rmtree(deploy_dir)


def get_ssh_user(name: str) -> str:
    """Get the SSH user for a deployment (from inventory or provider default)."""
    # Try to read from inventory
    inventory_path = get_deployment_dir(name) / "inventory.ini"
    if inventory_path.exists():
        try:
            content = inventory_path.read_text()
            match = re.search(r'ansible_user=(\w+)', content)
            if match:
                return match.group(1)
        except OSError:
            pass

    # Fall back to provider defaults
    provider = get_deployment_provider(name)
    if provider == "aws":
        return "ubuntu"
    return "root"  # Hetzner, DigitalOcean
